### ISSUE TITLE
change/document that flask's default port 5000 is used by Mac for AirPlay Receiver

### ISSUE THREAD

**Issue by jkunze** [metadata-research/yamz#101]
This makes it hard to test on a Mac, where port 5000 on localhost or 127.0.0.1 is blocked without an informative message. I don't know a better fix than just to avoid it. Maybe there's a config var that will change the "flask run" default?

**Comment by cr625** [comment]
Check out the readme, #13 

export FLASK_RUN_PORT=xxxx
