### ISSUE TITLE
User Experience Enhancement: Page Redirect

### ISSUE THREAD

**Issue by EMiller34** [metadata-research/yamz#112]
On the Add Tab and the Import Tab are links to the "Community Guidelines" page.  Clicking these links directs the webpage to the community guidelines page.  

The problem: These two pages are forms the user is actively filling out. Overwriting the webpage risks erasing work that has been completed so far. 

The solution: Links on these pages should open in a new tab, not overwrite the current webpage.

**Comment by jkunze** [comment]
@EMiller34 please look at yamz-dev.yamz.net and let me know if this issue is fixed. (I'm establishing yamz-dev under a new role account and using this small issue to exercise the operations side of things.)

**Comment by EMiller34** [comment]
@jkunze looks good! the links on each page are redirecting appropriately!

**Comment by jkunze** [comment]
Didn't mean to close it just yet. Wanted to do it as part of merge.
