### ISSUE TITLE
Make browse page title: YAMZ Browse

### ISSUE THREAD

**Issue by jkunze** [metadata-research/yamz#12]
Currently the title is "A basic page"

**Comment by machawk1** [comment]
This appears to be the case on yamz.link:
![title_link](https://user-images.githubusercontent.com/2514780/152016470-f55a28f6-ed32-444a-b844-680991d244a5.png)

...but not yamz.net:
![title_net](https://user-images.githubusercontent.com/2514780/152016579-5b6a8ff0-37b1-4726-af4d-bac41a38b0bc.png)

**Comment by cr625** [comment]
changed with latest commit #
