### ISSUE TITLE
moths

### ISSUE THREAD

**Issue by jkunze** [metadata-research/yamz#123]
**Describe the bug**
There are moths in my closet.

**To Reproduce**
1. Go to the closet
2. Open the door
3. Watch them flutter out

**Expected behavior**
No moths is better.

**Desktop (please complete the following information):**
 - OS: all
 - Browser all

**Smartphone (please complete the following information):**

**Additional context**

**Please add any other applicable labels and submit**

**Comment by cr625** [comment]
The Venezuelan Poodle Moth is the coolest moth ever.
https://factanimal.com/venezuelan-poodle-moth/

**Comment by EMiller34** [comment]
Test issue

**Comment by jkunze** [comment]
Yes, the Venezuelan Poodle Moth is amazing.
