### ISSUE TITLE
Suppress emails in comments and user record

### ISSUE THREAD

**Issue by EMiller34** [metadata-research/yamz#129]
**Describe the bug**
When users submit comments, user names with emails are displayed.  

**To Reproduce**
Go to term
Add comment
User's name is displayed as an active link to the email address in their profile. 

**Expected behavior**
Email is personal information, and should not be displayed. 

First and last name is also personal information.  There should be a warning in the profile section that this is the "public" information for the account holder.  

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All (untested)

**Additional context**

**Please add any other applicable labels and submit**

**Comment by jkunze** [comment]
Pushed into production after preliminary signoff from Scott M.
