### ISSUE TITLE
Single word search inside term string bug

### ISSUE THREAD

**Issue by jkunze** [metadata-research/yamz#136]
**Describe the bug**
*Search not working on single words in multi-word term string*

**To Reproduce**
*Steps to reproduce the behavior:*  

produces 4 results, but search on coronal produces 0 results and on ejection produces 1 result (but no overlap with the 4 results from the first search.
*1. Search on "coronal mass ejection" (4 results)*  
*2. Search on "coronal" (0 results)*  
*3. Search on "ejection" (1 result but not overlap with prior results)*  

**Expected behavior**  
*Term string probably needs to have ts_vector support*

**Desktop (please complete the following information):**  
 *- OS: Mac OS*  
 *- Browser: Brave*

**Comment by cr625** [comment]
I changed the term_string match to a regular expression in the term search [view](https://github.com/metadata-research/yamz/blob/main/app/term/views.py)

term_string_re = "(?i)(\W|^)(" + re.escape(search_terms).replace(" ","|")+ ")(\W|$)"

It's a bit permissive, so if it's If it's not exactly right, you can change the regular expression to the rules you want to use. The term string is a separate retrieval from the search vector, so the search terms will return the term string matches first and then the tags and finally then within the context of the definition and explanation.
