### ISSUE TITLE
Make sure redirect on n2t.net points to the correct server (id.cci.drexel.edu)

### ISSUE THREAD

**Issue by cr625** [metadata-research/yamz#33]

**Comment by cr625** [comment]
This actually seems to work pointing at yamz.net

**Comment by jkunze** [comment]
Actually, someone pointed out that the current redirect isn't quite working and persistent links to terms are broken. Example: http://yamz.net/term/concept=h1576 returns just the homepage. Maybe there's an adjustment to the forwarding to make sure whatever path arrives is forwarded along with the domain name?

**Comment by cr625** [comment]
I added back $request_uri to the redirect. Last time it caused problems with the http/s redirect. Seems to be working now but worth a test.

**Comment by jkunze** [comment]
Great. Looks good to me too.
