### ISSUE TITLE
Assemble a list of publications relating to YAMZ

### ISSUE THREAD

**Issue by machawk1** [metadata-research/yamz#35]
For example, @jkunze uploaded https://archive.org/details/Metadictionary--Advocating-for-community-driven-metadata-vocabulary-application to IA but it would be useful to have a list of all related papers, references, and ideally a link to the paper/PDF.

**Comment by cr625** [comment]
This could go on the MRC web page for YAMZ in wordpress.

**Comment by cr625** [comment]
at the bottom of the page, here: https://cci.drexel.edu/mrc/yamz-metadata-dictionary/
