### ISSUE TITLE
Some GCW terms have redundant tag at end of definition

### ISSUE THREAD

**Issue by jkunze** [metadata-research/yamz#54]
Example: http://127.0.0.1:5000/term/ark/h6894
has a tag "IHPGlacierMassBalance" as well as an orphaned word "IHPGlacierMassBalance" at the end of the definition.

**Comment by cr625** [comment]
Removed the majority of these with a script. The removal/conversion of (ambiguous) tags is its own issue here, so that still needs to be done. If there are a few strays, it would be fine to remove them manually. If it's more than that, maybe we can create  new issue.
