### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by jkunze** [metadata-research/yamz#96]
Could we incorporate a favicon.ico file? I pushed one on the jakkbl branch, but don't know where it should live in the source tree, but from the web server browsers will try to fetch /favicon.ico automatically.

**Comment by cr625** [comment]
images are set to load from here: app/static/images
referencing them in the template uses the url_for syntax: <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}">

Right now pre-development branch (i.e. my computer) the image is just a black square?

**Comment by jkunze** [comment]
Hmm. Shouldn't be a black square. I produced it with converticon.com and then downloaded. Looked fine at their site, but when I open it with Mac Preview I don't see anything.

Unix "file" says:  favicon.ico: MS Windows icon resource - 1 icon, -128x-128, 32 bits/pixel

**Comment by jkunze** [comment]
I just remade the favicon.ico file on my branch, added the original higher res images, moved them into app/static/images, and pushed to GH. The new favicon.ico file opens much better now on Mac Preview. How does it look to you?

**Comment by cr625** [comment]
https://yamz-dev.yamz.net/
![image](https://user-images.githubusercontent.com/70023998/217320916-a4f716e0-8e11-4f7c-a13b-cc3b8f3e531e.png)
